### ISSUE TITLE
No tag for release 2.0.0.0

### ISSUE THREAD

**Issue by ott** [hamcrest/JavaHamcrest#101]
Release 2.0.0.0 does not have a proper tag and therefore does not appear in the [releases feed](https://github.com/hamcrest/JavaHamcrest/releases.atom).

**Comment by paulduffin** [comment]
I assume that the 2.0.0.0 branch is the one that is the source for https://mvnrepository.com/artifact/org.hamcrest/java-hamcrest/2.0.0.0 and https://mvnrepository.com/artifact/org.hamcrest/hamcrest-junit/2.0.0.0.

What is the difference between 2.0.0.0 and 2.x and master?

**Comment by paulduffin** [comment]
To answer my own question (as much as I can from the git history) 2.x is a dead end - has not been worked on since 2014. 2.0.0.0 is almost the same as master - there are about 7 significant changes made since the commit that is common to both (f540af9fd49f33cc07b3446a8895c7b51cbf0944). Those changes are incompatible, based on the fact that there are some conflicts when attempting to merge v2.0.0.0 into master.

**Comment by sf105** [comment]
Sigh. I had a pretty good plan, but took so long over it (what with the rest of my life) that it went out of date. For now, I'm trying to find out what happened to the hamcrest.org domain. Perhaps it's time to resurrect a proper committers group...

**Comment by Thunderforge** [comment]
@sf105 There were a number of interested committers in #131. Perhaps reaching out to them would be the right way to resurrect a committers group.

**Comment by wltjr** [comment]
Short of a new release, could use tags for 2.0.0.0. Seems Junit4 has switched to using that, and no longer builds against 1.3.x. For the time being I will fork and tag for my needs. Though would much prefer tags come from upstream.

**Comment by wltjr** [comment]
@sf105 I am happy to help with getting a new release out and setting up CI stuff, like what I did for [JTidy](https://github.com/jtidy/jtidy) and I do for all my repos. Once JTidy is furthered and some issues fixed will modify it to auto deploy on tag to maven and gradle repos along with a jar under releases. Not sure about helping to maintain and further code, but I can at least help on the CI/deployment/release front.

**Comment by tumbarumba** [comment]
2.0.0.0 wasn't tagged, but all changes were rolled up into the 2.1 release
