### ISSUE TITLE
Hamcrest should be an osgi bundle

### ISSUE THREAD

**Issue by rgrunber** [hamcrest/JavaHamcrest#11]
I've seen discussion of this at http://code.google.com/p/hamcrest/issues/detail?id=173 , and the topic has come up in regards to doing the same for Junit (https://github.com/KentBeck/junit/issues/212). Is there any plan for this ?

**Comment by cvgaviao** [comment]
Any news about this issue?

**Comment by josephw** [comment]
@cvgaviao This is addressed by #98 . If you're an interested OSGi user, please comment over there to confirm that it's a fix.
