### ISSUE TITLE
Implement equals in Matchers

### ISSUE THREAD

**Issue by alechenninger** [hamcrest/JavaHamcrest#111]
If you have an API which uses Matcher, it is difficult to mock methods because matchers are only equal by JVM identity.

ie instead of...
```java
        when(context.findAllByUrl(Browser.class, equalTo("foo"))).thenReturn(found);
        assertSame(found, By.url("foo").findAll(Browser.class, context));
```

I have to do...
```java
        Matcher equalToFoo = equalTo("foo");
        when(context.findAllByUrl(Browser.class, equalToFoo)).thenReturn(found);
        assertSame(found, By.url(equalToFoo).findAll(Browser.class, context));
```

With mockito this can be mitigated with using `refEq()` in the `when` stubbing, but IMHO it's easy enough for IDE's to generate good equals methods that it's not unreasonable to expect them to be implemented.

Cheers

**Comment by npryce** [comment]
What do you mean by equal?

Should a matcher implemented as (value == 1 || value == 2) be equal to anyOf(equalTo(1), equalTo(2))?

Even if you resolved this question to everyone's satisfaction, you'd have to submit a PR to implement equals and hashCode for all the matchers in Hamcrest-Java and all the extension libraries that implement Matcher!  I think this bird has flown.

**Comment by alechenninger** [comment]
Thanks for the reply! I realize that would require updating a lot of matchers, but I don't see why it has to be all or nothing (particularly re: extension libraries).

I would keep it simple. `assertTrue(equalTo(1), equalTo(1))`. Each Matcher implementation can only be equal to another of the same implementation. If two have logically the same match but are different classes, they are unequal. The IntelliJ auto-generated equals/hashcode template I think would satisfy this requirement quite reasonable. Perhaps you could use a tool like that to implement them in one batch?

Writing a fake context with map implementation seems more complicated to me than stubbing one method.

**Comment by sf105** [comment]
Another way of looking at this is that it's such an usual case (testing the use of Matchers, rather than using Matchers to test other code), that you should consider writing your own for the purpose of your test. Perhaps write one that does what you want and then delegates to a standard matcher for the behaviour? 

On the other hand, it looks as if you're testing a DSL construction. Quite often, we just do more integration tests at that level, relying on lower-level tests for the detail.

**Comment by npryce** [comment]
"Each Matcher implementation can only be equal to another of the same implementation"

That leaks implementation details beyond the interface.  It must be possible to change the implementation class without breaking client code, otherwise we'd not be able to change the classes instantiated by syntactic sugar factory methods (which we sometimes do to improve mismatch messages or performance).

**Comment by alechenninger** [comment]
> That leaks implementation details beyond the interface

Good point. Perhaps rather than thinking about it in terms of implementations, think about it in terms of the API then. Is it a reasonable rule to say that if you use two different APIs (like `is` and `equalTo`) there is no guarantee that they will be equal or not even if they are logically equivalent? This would give you freedom to change the implementations. If you are comparing two matcher instances from the same API, then of course they will be (unless there is some conditional logic or something surprising) the same implementation. IMHO this is what i would like to see. You could reason about equivalence as, "using the same language" (API + parameters) as opposed to "same instance."

> Another way of looking at this is that it's such an usual case (testing the use of Matchers, rather than using Matchers to test other code), that you should consider writing your own for the purpose of your test.

Not a bad idea. Although, I'm employing hamcrest as use in a src/main library (to be used in tests, but I digress). Hamcrest is quite nice as a general purpose matcher library :). In this application it would be useful if matchers followed equivalence rules like suggested above. In my case this would mean to "locators" that match using equivalent matchers would be equal, which makes sense, and is useful beyond my unit tests. Otherwise, these locators will only be equal if the same instance of the matcher is used, which is less useful.

Thanks for the replies!

**Comment by sf105** [comment]
Sorry, but I think this case is too obscure, plus it raises the bar for people implementing their own matchers--don't forget it needs `hashCode()` too.
