### ISSUE TITLE
Correct generics usage in Matcher<T> and implementing classes

### ISSUE THREAD

**Issue by RAnders00** [hamcrest/JavaHamcrest#114]
Matcher<T> could be using type T in .matches()

`Matcher.java`
```java
boolean matches(T item);
void describeMismatch(T item, Description mismatchDescription);
```

Obviously, you would have to refactor all underlying implementations as BaseMatcher<T>, etc.

This would remove pointless casting of the object.

**Comment by sf105** [comment]
It's like this for the same reason that equals() takes Object, we don't want to overspecify the type of the actual object. As library writers, we don't know how people will want to use this, including whether they've managed to retain the actual type in the calling code. We've provided TypeSafe subclasses to simplify the implementation where this matter.

**Comment by RAnders00** [comment]
What is this typesafe subclass?

**Comment by sf105** [comment]
http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/TypeSafeMatcher.html

Perhaps a little more time investigating the existing code?

**Comment by wlei07** [comment]
I would say it is better to remove junk generic <T> from BaseMatcher<T>, as it is not used and type safe anyway.
