### ISSUE TITLE
Add Javadoc for JavaHamcrest 2.0.0.0 to hamcrest.org

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [hamcrest/JavaHamcrest#117]
hamcrest.org currently only shows the Javadoc for JavaHamcrest 1.3:
http://hamcrest.org/JavaHamcrest/javadoc/

**Comment by dcsobral** [comment]
I wasn't even aware of Hamcrest 2.0.0 until I searched for a way to check a map for emptyness.

**Comment by massenz** [comment]
I see the commit, but the javadocs still appear not to be reachable from hamcrest.org?
http://hamcrest.org/JavaHamcrest/javadoc/

still shows this:
![screen shot 2016-07-11 at 1 51 15 pm](https://cloud.githubusercontent.com/assets/1153951/16746301/93d9d286-476e-11e6-99c2-5bc09aa85816.png)

How do we get to see the Javadocs?
Thanks.

**Comment by arend-von-reinersdorff** [comment]
@massenz The pull request is still open.

In the meantime you can see the Javadoc for version 2.0.0.0 here:
http://javadoc.io/doc/org.hamcrest/java-hamcrest/2.0.0.0

**Comment by massenz** [comment]
Cool, thanks!

**Comment by tiagomestreteixeira** [comment]
I was like the @dcsobral , after some deeper search i found the version 2.0.0.0 because of the method IsMapWithSize. @arend-von-reinersdorff thank you for the link. There is still only javadocs v1.3 at http://hamcrest.org/JavaHamcrest/javadoc/
