### ISSUE TITLE
java-hamcrest 2.0.0.0 imports redundant dependency

### ISSUE THREAD

**Issue by toolforger** [hamcrest/JavaHamcrest#126]
I have `testCompile 'org.hamcrest:hamcrest-junit:2.0.0.0'` in my `build.gradle`.
`gradle dependencies` tells me this:

```
\--- org.hamcrest:hamcrest-junit:2.0.0.0
     +--- junit:junit:4.12
     |    \--- org.hamcrest:hamcrest-core:1.3
     \--- org.hamcrest:java-hamcrest:2.0.0.0
```

Result is that packages `org.hamcrest`, `org.hamcrest.core`, and `org.hamcrest.internals` are present twice, with diverging classes, in `hamcrest-core-1.3.jar` and `java-hamcrest-2.0.0.0.jar`.

I don't know what the actual problem is: that `hamcrest-junit` depends on `junit`, or that `junit` depends on `hamcrest-core`, or maybe the `hamcrest-junit` pom should declare that `junit`'s dependency on `hamcrest-core` should be ignored.

At best, people will see 1.3 functionality where they expect 2.0 functionality.
At worst, they'll get a class loader configuration that mixes 1.3 and 2.0 classes.

**Comment by sf105** [comment]
Presumably, this is a junit issue. In our gradle.build file we have 
```
dependencies {
    testCompile(group: 'junit', name: 'junit', version: '4.12') {
        transitive = false
    }
}
```
You might need to do something similar.
