### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by hzsweers** [hamcrest/JavaHamcrest#131]
Noticed that there's been no commits since june, no documentation on the v2 release, and no responses to issues or PRs in the past 2-3 months.

**Comment by sf105** [comment]
As you may have noticed, we have a bit of a committer crisis. We did some work on it last year, but have been too busy with the day job and not working much in Java. We invited a couple of people to get involved but then they got busy too (getting volunteers is never a problem, getting active volunteers is).

Personally, I have some ideas about how the library should evolve but got stuck.

I'm now thinking that we should take proposals for people who want to become committers.

S

**Comment by erosb** [comment]
@sf105 I'm interested in becoming a hamcrest committer. Should I send some kind of introduction? I couldn't find your email address anywhere.

**Comment by npathai** [comment]
@sf105 I would like to raise my hand.

**Comment by trirano** [comment]
@sf105 sf105  You can also count on me

**Comment by erosb** [comment]
@sf105 could you please reply for any of us? Thanks.

**Comment by gokhanbarisaker** [comment]
@sf105 at your service :)

**Comment by erosb** [comment]
@sf105 any update, please?

**Comment by TWiStErRob** [comment]
@sf105 1 year since the first volunteer, lucky 1.3 is rock solid for most use cases

Is there a roadmap of outstanding features before it can be released?

**Comment by rkcpi** [comment]
Any news on this?

**Comment by tusharjoshi** [comment]
Is there any way to know pending tasks on this project?  I will be able to help this month in any way possible.  Any mailing list where we can discuss?  I am interested in the priority of the issue list so I can start looking into the issues where possible.

**Comment by sf105** [comment]
You'll noticed that @tumbarumba has been doing some sterling work to sort out a new generation of releases.

**Comment by tumbarumba** [comment]
Thanks, Steve!

Well, #224 is done. I haven't really thought about the priority of other issues, or a roadmap. I see that that @sf105 has been applying the `Hamcrest future` label. There needs to be a discussion (on the mailing list, perhaps) about what the future of Hamcrest should be. However, there are always documentation updates and bug fixes. Pull requests are always appreciated!

I'm going to close this issue, as I'm planning on sticking around for a bit. If the project appears to be non-responsive again in the future, feel free to jump right in!
