### ISSUE TITLE
Clarify documentation for single Matcher Matchers.contains variant

### ISSUE THREAD

**Issue by gsmith85** [hamcrest/JavaHamcrest#133]
The following variant of contains:

```
  public static <E> org.hamcrest.Matcher<java.lang.Iterable<? extends E>> contains(org.hamcrest.Matcher<? super E> itemMatcher) {
    return org.hamcrest.collection.IsIterableContainingInOrder.<E>contains(itemMatcher);
  }
```

Has documentation that would lead one to believe that the following code snippet would pass:

```
assertThat(ImmutableList.of("green", "red"), contains(startsWith("green")));
```

As it specifies "matches when a single pass over the examined Iterable yields a single item that satisfies the specified matcher".

It is not at all made clear that for `contains` to match, every item in the collection must have a matcher, and in the case of this `contains` variant, you can only ever match a `Collection` of length one!

I suggest we make the documentation a bit more clear in this situation.  I'm willing to put together the PR if others believe this would be useful.

**Comment by sf105** [comment]
I think it does actually say that. This should be part of a bigger change described in #140
