### ISSUE TITLE
Rename the distributed jar file

### ISSUE THREAD

**Issue by ogregoire** [hamcrest/JavaHamcrest#135]
In naming, it's irrelevant to use "java"-hamcrest. Maven, gradle and friends supports only Java libraries, and the complete file name (java-hamcrest.jar) already mentions it's a java library (with the extension).

Also, the name in itself is prone to confusion. When you're used to search for either "hamcrest-core" or "hamcrest-all", in an IDE, you type the group-id, then the first letters ("ham", for instance) and don't get the latest version because it's already been filtered out.

Okay, you're on GitHub, you have several projects for several languages but this doesn't need to be reflected when the context is obvious. So please keep the separation between your project name and what people will have to use on a daily basis.

**Comment by tumbarumba** [comment]
Fixed in 2.1
