### ISSUE TITLE
Name of method: equalToIgnoringWhiteSpace

### ISSUE THREAD

**Issue by Lord0** [hamcrest/JavaHamcrest#141]
This method is incorrectly named.

It does NOT ignore ALL whitespace.

From the doc:

Creates a matcher of String that matches when the examined string is equal to the specified expectedString, when whitespace differences are (mostly) ignored. To be exact, the following whitespace rules are applied:

- all leading and trailing whitespace of both the expectedString and the examined string are ignored
- any remaining whitespace, appearing within either string, **is collapsed to a single space before comparison**

So **some** space is removed but not all...

Edit: maybe call it **equalToIgnoreWhiteSpaceMostly**?

**Comment by BryanDollery** [comment]
What about -- equalToIgnoringSuperfluousWhitespace?

**Comment by sf105** [comment]
renamed to equalToCompressingWhiteSpace, equalToIgnoringWhiteSpace has been deprecated.

**Comment by Lord0** [comment]
Nice thats perfect
