### ISSUE TITLE
Same List<Long> is not same according to containsInAnyOrder

### ISSUE THREAD

**Issue by cimnine** [hamcrest/JavaHamcrest#142]
Take the following example:

    @Test
    public void compareSameList() {
      // given
      List<Long> expected = Arrays.asList(100L, 101L, 200L, 201L, 300L, 301L, 400L);
  
      // then
      assertThat(expected, containsInAnyOrder(expected));
    }

This results in:

    java.lang.AssertionError: 
    Expected: iterable over [<[100, 101, 200, 201, 300, 301, 400]>] in any order
         but: Not matched: <400L>

I would expect the Lists to be the same, but the ``containsInAnyOrder`` Matcher claims that one element is missing, usually 100L or 400L.

**Comment by cimnine** [comment]
Never mind, I got it:

    @Test
    public void compareSameList() {
      // given
      List<Long> expected = Arrays.asList(100L, 101L, 200L, 201L, 300L, 301L, 400L);
  
      // then
      assertThat(expected, containsInAnyOrder(expected.toArray()));
    }

**Comment by amomchilov** [comment]
Hah, this helped me, thanks!

If you pass in a `List<Long>`, the `T...` overload infers `T` to be `List<Long>`, not `Long`, so it's checking if your list contains the whole list as a member, rather than the list members as members.
