### ISSUE TITLE
TypeSafeDiagnosingMatcher.matchesSafely is called twice in case of mismatch

### ISSUE THREAD

**Issue by SubOptimal** [hamcrest/JavaHamcrest#144]
In case of a failed match the method `matchesSafely` is called twice. This behavior should be mentioned in the Javadoc as it might have unexpected side effects on the executed check inside (see an example from SO [1]).

Analogous to an example in `IsCollectionContainingTest.java` an example could be implemented as

    public class TypeSafeDiagnosingMatcherTest {

        @Test
        public void foo() {
            Stream<String> stream = Stream.of("foo", "bar");
            assertThat(stream, hasCount(3));        
        }

        // analogous to IsCollectionContainingTest.java#L89
        Matcher<Stream> hasCount1(int count) {
            return new TypeSafeDiagnosingMatcher<Stream>() {
                @Override
                protected boolean matchesSafely(Stream stream, Description desc) {
                    long streamCount = stream.count();
                    if (streamCount == count) {
                        return true;
                    }
                    desc.appendText("has count ").appendValue(streamCount);
                    return false;
                }

                @Override
                public void describeTo(Description desc) {
                    desc.appendText("count ").appendValue(count);
                }
            };
        }

The mismatch message is not as expected `foo Failed: Expected: count <3>    but: has count <2>` it is `foo  caused an ERROR: stream has already been operated upon or closed`. This is related to the fact that after the first execution of `matchesSafely` to get `stream.count()` the stream is closed. The second time `matchesSafely` is called aftert `describeTo` to generate the description.

The workaround to handle the second (unexpected method invocation) is

    Matcher<Stream> hasCount(int count) {
        return new TypeSafeDiagnosingMatcher<Stream>() {
            Optional<Long> streamCount = Optional.empty();

            @Override
            protected boolean matchesSafely(Stream stream, Description desc) {
                if (streamCount.isPresent()) {
                    desc.appendText("has count ")
                            .appendValue(streamCount.get().intValue());
                } else {
                    streamCount = Optional.of(stream.count());
                }
                return streamCount.get() == count;
            }

            @Override
            public void describeTo(Description desc) {
                desc.appendText("count ").appendValue(count);
            }
        };
    }

The fix should be either to mention the second invocation in the Javadoc or to avoid the second execution in case of a non-match. Anyway the second invocation looks a bit weird, as for the first invocation the check determines the non-match the description object is popolated and later not used. Because only the description object of the second invocation will be used for the logged message.

An matcher for demonstration

    Matcher<Stream> hasCount(int count) {
        return new TypeSafeDiagnosingMatcher<Stream>() {
            int step = 0;

            @Override
            protected boolean matchesSafely(Stream stream, Description desc) {
                step++;
                System.out.printf("step: %d   matchesSafely: >[%s]<%n", step, desc.toString());
                return false;
            }

            @Override
            public void describeTo(Description desc) {
                step++;
                System.out.printf("step: %d   describeTo: >[%s]<%n", step, desc.toString());
            }
        };
    }

Produced output

    step: 1   matchesSafely: >[]<
    step: 2   describeTo: >[
    Expected: ]<
    step: 3   matchesSafely: >[
    Expected: 
         but: ]<

1. the first call of `matchesSafely` which returns `false`
2. call of `describeTo` to produce the description
3. the second call of `matchesSafely` to append the `but:` part of the not-matched description

cheers
Frank

[1] a question on StackOverflow http://stackoverflow.com/questions/36442819/creating-a-matcherstream-for-junit

**Comment by sf105** [comment]
In the mists of time, we made a decision that we do not guarantee how often any of the matches methods might be called. I'm not sure where best to document this as I doubt if anyone actually reads the Javadoc for Matcher. In the short term, a better workaround would probably be to collect the stream and match against that.

**Comment by SubOptimal** [comment]
I agree that for the provided Stream example other/better solutions exist to check the count. On the other side it is a good example for the unexpected behavior of possible edge case uses. The same behavior happen with the `TypeSafeMatcher`.

For the Javadoc maybe a hint would be enough to mention that any method of `item` invoked inside the `matches` methods should be idempotent and should not change the state of `item`. As the state of `item` after the invocation of the matcher class might be unpredictable.

**Comment by sf105** [comment]
I've added comments to the Matcher interface

**Comment by SubOptimal** [comment]
Great. Thank you.

**Comment by dzieciou** [comment]
@sf105  "I'm not sure where best to document this as I doubt if anyone actually reads the Javadoc for Matcher." -- I do read.
