### ISSUE TITLE
IsCloseTo doesn't work with infinity

### ISSUE THREAD

**Issue by xavierbeynon** [hamcrest/JavaHamcrest#145]
Presumably, any pair of doubles that match equalTo should also match closeTo with the epsilon set to 0.

`MatcherAssert.assertThat(Double.POSITIVE_INFINITY,IsCloseTo.closeTo(Double.POSITIVE_INFINITY, 0d));`

`Exception in thread "main" java.lang.AssertionError: 
Expected: a numeric value within <0.0> of <Infinity>
but: <Infinity> differed by <NaN>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
...`

**Comment by sf105** [comment]
The problem here is subtracting one infinity from another, which is Not A Number. I don't think it's worth us handling this.

**Comment by xavierbeynon** [comment]
Why?  Are you asking for a pull request?
