### ISSUE TITLE
Improve SamePropertyValuesAs to allow extension to ignore fields

### ISSUE THREAD

**Issue by dcw312** [hamcrest/JavaHamcrest#170]
Problem SamePropertyValuesAs does not support ignoring fields

Either:

1. change private methods to protected so the class can be enhanced to ignore certain properties, or
2. add the feature to ignore fields in this class

I'm willing to make the change. Please let me know if this feature is intentionally omitted.

Thanks!

**Comment by diarmuidkeane** [comment]
+1

**Comment by wdinau** [comment]
+1
my user case = 
source = pojo
target = returned from db with db generated id and datetime stamp
I'd like to be able to exclude those properties and compare all the rest.

**Comment by neuberg-tomas** [comment]
+1

**Comment by mmugur81** [comment]
+1

**Comment by piotrbo** [comment]
+1

**Comment by piotrbo** [comment]
+1

**Comment by dcw312** [comment]
I have started a fork to implement.

**Comment by feirorum** [comment]
+1

**Comment by samfraser** [comment]
+1

**Comment by mattmichal** [comment]
+1, my use case is similar to that of @wdinau although I'm not using an ORM tool.

**Comment by wykapedia** [comment]
+1, same use case as @wdinau

**Comment by Gozke** [comment]
I'd love this feature. I have a similar usecase to what @wdinau described above.

**Comment by sf105** [comment]
done.

**Comment by sf105** [comment]
It's pushed in the repo. Could you try to check it out and see if it does what you want?
