### ISSUE TITLE
IsEmptyString JavaDoc says null is matched

### ISSUE THREAD

**Issue by ljacqu** [hamcrest/JavaHamcrest#171]
This is a minor finding but it would still be nice if it could be fixed. The JavaDoc on IsEmptyString says that `null` values are matched:

```java
/**
 * Matches empty Strings (and null).
 */
public final class IsEmptyString extends TypeSafeMatcher<String> {
```

The fact that it extends `TypeSafeMatcher` was a clear indication that this is not the case, and a test confirms this:
```java
    @Test
    public void shouldMatchNullAccordingToJavaDoc() {
        assertThat(null, org.hamcrest.Matchers.emptyString()); // fails
    }
```

Would it be possible to update the "and null" part from the JavaDoc?

**Comment by StarBax89** [comment]
emptyOrNullString method in this class matches null.

**Comment by sf105** [comment]
Thanks for contributing
