### ISSUE TITLE
Java 9 Quick Win Pre Modules

### ISSUE THREAD

**Issue by nhojpatrick** [hamcrest/JavaHamcrest#185]
Quick win for supporting Java 9.

I'm assuming once you fully support Java 9 Modules, you would probably pick the module name of "org.hamcrest", assuming that I've done a quick patch so if hamcrest is added as a module before it's setup correctly as a module, then it's loaded as an automatic module with a name match what i'm guessing you would be using.

References; http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

Pull Request arriving shortly

**Comment by tumbarumba** [comment]
Merged PR #186
