### ISSUE TITLE
Matcher.matches needs to have parameterized argument

### ISSUE THREAD

**Issue by krichter722** [hamcrest/JavaHamcrest#199]
Generics are hard to understand and a wonderful thing after you did. Roughly speaking, the description

```
public interface Matcher<T> extends SelfDescribing {

    /**
     * Evaluates the matcher for argument <var>item</var>.
     *
     * This method matches against Object, instead of the generic type T. This is
     * because the caller of the Matcher does not know at runtime what the type is
     * (because of type erasure with Java generics). It is down to the implementations
     * to check the correct type.
     *
     * @param actual the object against which the matcher is evaluated.
     * @return <code>true</code> if <var>item</var> matches, otherwise <code>false</code>.
     *
     * @see BaseMatcher
     */
    boolean matches(Object actual);
```

shows that generics have not been understood by the author.

> This is because the caller of the Matcher does not know at runtime what the type is (because of type erasure with Java generics)

The opposite (almost) is the case. If you specify a `Matcher` (without generics) as static type the matcher doesn't know the type at runtime - how could it. If you specify a `Matcher<SomeType>` you either

  1. are accessing it at least once as `Matcher` and might get `ClassCastException`s, but also an `unchecked` conversion or `rawtypes` warning which you shouldn't take easy in Java - roughly speaking you get what you deserve or
  2. you use `Matcher<SomeType>` everywhere you don't get warning or compilation errors the Matcher knows _exactly_ which type the argument is at runtime.

`2.` allows to write awesome cast- and type-check-free code in Java and `1.` allows you to do what you want by omitting the generic type on static type of callers, but still be able to enforce maximum type safety in interfaces and thus allow others to stick with `2.`.

It makes sense that the parameter is not used if you don't use it in `matches`.

Once this is fixed the type-safety could be expanded to factory methods like `public static org.hamcrest.Matcher<java.lang.Object> anything()` in `Matchers` which could be `public static <T> org.hamcrest.Matcher<T> anything()` invoking

```
public static <T> Matcher<T> anything(String description) {
    return new IsAnything<>(description);
}
```

Since getting a `Matcher<Object>` if you could have a `Matcher<T>` with no harm done to any other user is slightly painful.

I'm willing to submit a PR if you ok it.

**Comment by sf105** [comment]
Thanks for contributing. Please see the pull request message.

One point to make is that we're very picky about our mismatch descriptions because matchers are used in other situations than unit tests. It's a conscious design choice not to just let things fail.
