### ISSUE TITLE
Gradle back to Maven

### ISSUE THREAD

**Issue by nhojpatrick** [hamcrest/JavaHamcrest#208]
Hamcrest future

Lots of projects I noticed switched to Gradle, but I've also noticed a change where projects move back to Maven.

- Java 9 support was more stable in Maven earlier than Gradle.
- Gradle plugins appear more flaky with each Gradle version than Maven plugins
- Gradle is yes powerful but it feels like Ant, you can do a lot but to understand what it is doing you need to be an expert as it is so flexible.
- Maven yes can be a massive amount of xml, but it's also very structures with more standards so junior developers/contributed/maintainers might be able to contribute earlier.

**Comment by thespags** [comment]
@nhojpatrick Can you mark the issues you've created with the label "hamcrest future" as well?

**Comment by nhojpatrick** [comment]
@thespags I don't have permission to add labels. The options I see in my public/private repo's to add labels, don't show on this repo.

**Comment by thespags** [comment]
Oh! My mistake, thought it was the owner of the issue. Thanks for bringing more spotlight to reviving hamcrest. The slack channel fizzled out at the New Year.

**Comment by sf105** [comment]
I'm open to this as I don't see much difference in practice for us between the two. I know it's a pain, but do you have the time to create a pull request?

**Comment by Thunderforge** [comment]
To be the dissenting voice:

> Java 9 support was more stable in Maven earlier than Gradle.

They both support Java 9 and Java 10 now, so why does this matter?

> Gradle plugins appear more flaky with each Gradle version than Maven plugins

If this were Wikipedia, I'd add `[citation needed]`. I have no idea where this perception comes from, and I have had no issues with plugins with newer versions of Gradle.

> Gradle is yes powerful but it feels like Ant, you can do a lot but to understand what it is doing you need to be an expert as it is so flexible.

As someone who has used Ant, Maven, and Gradle, I have no idea what is leading you to this conclusion. It sounds to me like it might be a matter of personal preference and familiarity. (Full disclosure: I personally prefer Gradle out of the three).

> Maven yes can be a massive amount of xml, but it's also very structures with more standards so junior developers/contributed/maintainers might be able to contribute earlier.

What structures? What standards? I have no idea what you're referring to. Is it just stuff like the [build lifecycle](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)? Gradle [has that too](https://docs.gradle.org/current/userguide/build_lifecycle.html).

Without further information, I don't see the point of switching from Gradle to Maven. If it's only about personal preference, then we might as well debate spaces vs. tabs as well.

**Comment by tumbarumba** [comment]
I'm happy to keep Gradle
