### ISSUE TITLE
Clear up dead code

### ISSUE THREAD

**Issue by krichter722** [hamcrest/JavaHamcrest#213]
[IsMapContainingTest contains commented out methods which are associated with a comment stating that they no longer compile and need to be investigated](https://github.com/hamcrest/JavaHamcrest/blob/8f9372a152612b45f51a12d1c549643fdac5492a/hamcrest-library/src/test/java/org/hamcrest/collection/IsMapContainingTest.java#L30) (and [line 49](https://github.com/hamcrest/JavaHamcrest/blob/8f9372a152612b45f51a12d1c549643fdac5492a/hamcrest-library/src/test/java/org/hamcrest/collection/IsMapContainingTest.java#L49)). I assume that the investigation has been forgotten. The code should be fixed or moved to a separate branch.

Other classes, like `IsCompatibleTypeTest`, contain commented-out code without a comment. It should be fixed or removed as well.

**Comment by sf105** [comment]
done
