### ISSUE TITLE
Let Hamcrest compare a Date object against a Date String representation

### ISSUE THREAD

**Issue by manueljordan** [hamcrest/JavaHamcrest#239]
Hello Mancrest

For more details here:

* [Hamcrest: comparing Date against Date (String representation)](https://stackoverflow.com/questions/50080246/hamcrest-comparing-date-against-date-string-representation)

The point is have the following possible:

* `.andExpect(model().attribute("persona", hasProperty("fecha", is("08/12/1977"))))`
* `.andExpect(model().attribute("persona", hasProperty("fecha", is("1977-12-08"))))`

Thank You.

**Comment by tumbarumba** [comment]
Hamcrest does not parse or serialise dates. Perhaps the Hamcrest Date library (on the [Related Projects](http://hamcrest.org/JavaHamcrest/related) page) would be useful?
