### ISSUE TITLE
Let Hamcrest compare a XML's node directly against a Java object

### ISSUE THREAD

**Issue by manueljordan** [hamcrest/JavaHamcrest#240]
Hello Hamcrest

For more details here:

* [Spring MVC Test with Hamcrest: How compare a XML's node directly against a Java object](https://stackoverflow.com/questions/39476751/spring-mvc-test-with-hamcrest-how-compare-a-xmls-node-directly-against-a-java)

The point is have the following:

* `.andExpect(xpath("collection/item[1]/*").how(is(personasArray[0])))`
* `.andExpect(xpath("collection/item[1]/*").how(is(persona)))`

Thank You

**Comment by tumbarumba** [comment]
Your example is not Hamcrest, but appears to be part of Spring MVC Test
