### ISSUE TITLE
Provide back compatible StringContains constructors

### ISSUE THREAD

**Issue by philwebb** [hamcrest/JavaHamcrest#259]
Commit 639b99e58221ea4bc6fb914cab021e8e39e88259 changed the public constructors of `StringContains` `StringEndsWith` and `StringStartsWith` so that they now required an `ignoreCase` flag. This unfortunately can break anyone that happens to be calling those constructors directly rather than using the static factory methods.

Could additional constructors please be provided alongside the new ones so that Hamcrest 2.x remains compatible with earlier versions?

**Comment by philwebb** [comment]
For background, here's an example of a problem cause by the change: https://github.com/spring-projects/spring-boot/issues/15555#issuecomment-494889027

**Comment by tumbarumba** [comment]
Thanks @philwebb. I've just committed 86043c63cf6120e68895037b5213ac1f28e8df35. Does this fix the problem?

**Comment by sbrannen** [comment]
@tumbarumba, I don't see a milestone assigned to this issue.

Do you have an idea when this might be released?

**Comment by philwebb** [comment]
> Does this fix the problem?

@tumbarumba Looks good to me. Thanks for the fast turnaround!

**Comment by tumbarumba** [comment]
@sbrannen, we don't have a release planned, but having said that, there's been a few [bug-fixes](https://github.com/hamcrest/JavaHamcrest/blob/master/CHANGES.md) merged over the last few months, so I think it's worth pushing out a new release candidate. I'll make some time this weekend.

**Comment by sbrannen** [comment]
@tumbarumba, a bug fix release would be great! Thanks

**Comment by tumbarumba** [comment]
Just noticed I didn't closed this last year. It was fixed in release 2.2.
