### ISSUE TITLE
Please add LICENSE as META-INF/LICENSE, add Bundle-License header

### ISSUE THREAD

**Issue by vlsi** [hamcrest/JavaHamcrest#264]
1) Thanks for Hamcrest

2) Current hamcrest.jar are hard to bundle into other software due to missing licensing information.

Suggested changes are:

2.1) Package license as `META-INF/LICENSE`. Current one is `LICENSE.txt`, and de-facto standard is `META-INF/LICENSE`. The license files packaged at the root cause problems with Android.
Basically whoever makes an uberjar they have to implement "license merger", and typically they configure for `META-INF/LICENSE`.
2.2) Please add `Bundle-License: BSD-3-Clause` manifest entry (where `BSD-3-Clause` is SPDX identifier, see https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-bundle-license )
Unfortunately, there are lots of BSD-style licenses, and it is hard to tell what "New BSD License" means.
2.3) Even though 2.1 and 2.2 would be great, you might want to use BSD-3-Clause for `<licence><name>` tag in `pom.xml`. The use of SPDX in pom is not common yet, however BSD-3-Clause there would help even humans.

**Comment by tumbarumba** [comment]
This seems like a reasonable improvement. Are you able to create a pull request with these changes?

**Comment by vlsi** [comment]
@tumbarumba , here's a PR: https://github.com/hamcrest/JavaHamcrest/pull/399

**Comment by vlsi** [comment]
@tumbarumba , PR #414 does not include LICENSE file to the generated jar. Would you please include it?
