### ISSUE TITLE
The signature of isA is completely wrong

### ISSUE THREAD

**Issue by time4tea** [hamcrest/JavaHamcrest#27]
public static <T> org.hamcrest.Matcher<T> isA(java.lang.Class<T> type) {
    return org.hamcrest.core.Is.<T>isA(type);
  }

means you have to cast the thing to the type you are asserting it should be. Really it should be a matcher of anything (Object) not T.

e.g. 
class hierarchy Foo extends Bar

Bar thing = somemethod();
assertThat(thing, isA(Foo.class))

to assert that you are getting the right subclass back - yeah ok, it might not be the best test, but anyhow......

**Comment by bitzl** [comment]
I've submitted an Pull Request to fix this. The behavior of `isA` is documented as shortcut to `instanceOf`. I've enhanced tests to check if the beavior is similar and changed the methods return a `Matcher<?>` instead of `Matcher<TheClass.class>`.

**Comment by sf105** [comment]
Fixed

**Comment by massenz** [comment]
Could you please give us an indication of which version this was/will be released for?
I'm currently using `java-hamcrest:2.0.0.0` and it still has the same incorrect signature.

Thanks.

**Comment by durron597** [comment]
This change hasn't been released yet. I'm not a Hamcrest member so I can't tell when they plan to release the next one, but for now it looks like you'll have to build from source.

Unfortunately master still has the version number listed as 2.0.0.0, so you'd probably have to change that in your build if you're going to add it to a local repo.

**Comment by udalrich** [comment]
Any hope of this eventually being released?

**Comment by durron597** [comment]
I think the problem is that the version in `CoreMatchers` [never got fixed](https://github.com/hamcrest/JavaHamcrest/blob/master/hamcrest-core/src/main/java/org/hamcrest/CoreMatchers.java#L126)

**Comment by micheal-hill** [comment]
`hamcrest:2.1` has this problem...

**Comment by ProYI** [comment]
junit:4.13 depend on hamcrest-core:1.3 also has this problem

**Comment by nhojpatrick** [comment]
> `hamcrest:2.1` has this problem...

does `org:hamcrest:hamcrest:2.2` have the problem?

**Comment by nhojpatrick** [comment]
> junit:4.13 depend on hamcrest-core:1.3 also has this problem

feel free to raise PR with junit so v4.14 could be upgrade to the latest version, that being currently `org:hamcrest:hamcrest:2.2`

v1.x is dead and out of support
v2.x i'm still trying to learn the guts and help with patches... so semi in support
