### ISSUE TITLE
Wrong javadoc for stringContainsInOrder

### ISSUE THREAD

**Issue by Lyannic** [hamcrest/JavaHamcrest#272]
The javadoc for the stringContainsInOrder Matcher (http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#stringContainsInOrder(java.lang.Iterable))
states the following:
"Creates a matcher of String that matches when the examined string contains all of the specified substrings, **regardless of the order of their appearance**." 
But for me the name and also the functionality indicates that it isn't regardless of the order.

**Comment by tumbarumba** [comment]
Hi @Lyannic, you have linked to the old version of the JavaDoc (1.3). The latest version (2.1) has been update: http://hamcrest.org/JavaHamcrest/javadoc/2.1/org/hamcrest/Matchers.html#stringContainsInOrder-java.lang.Iterable-
