### ISSUE TITLE
Release Hamcrest 2.2

### ISSUE THREAD

**Issue by tumbarumba** [hamcrest/JavaHamcrest#273]
I'm preparing to release Hamcrest 2.2.

This issue is to capture any problems with the release candidates, and to discuss any changes that need to be made.

**Comment by tumbarumba** [comment]
I've tagged and published the first release candidate: [hamcrest-java-2.2-rc1](https://github.com/hamcrest/JavaHamcrest/releases/tag/v2.2-rc1). This is now available on Maven Central.

Please test this candidate and report any problems.

**Comment by quaff** [comment]
When?

**Comment by tumbarumba** [comment]
Now.

2.2 is now available from your favourite Maven Central mirror.
