### ISSUE TITLE
TLS is misconfigured on the site

### ISSUE THREAD

**Issue by dmitry-timofeev** [hamcrest/JavaHamcrest#280]
HTTP over TLS seems to be misconfigured on the hamcrest.org web site.

How to reproduce: go to https://hamcrest.org/JavaHamcrest/

Actual result: SSL_ERROR_BAD_CERT_DOMAIN

Expected: site loads correctly over https.

**Comment by tumbarumba** [comment]
@hamcrest/hamcrest-java-devs: this looks like a misconfiguration in https://github.com/hamcrest/hamcrest.github.com

I don't have full access to that repo, so I can't see the settings. Can someone with access have a look?

**Comment by sbrannen** [comment]
The Spring Framework just ran into this today.

> The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

It causes our Dokka task to fail: https://ge.spring.io/s/nvchmnxy3rf26/console-log?task=:spring-webmvc:dokkaHtmlPartial

**Comment by tumbarumba** [comment]
It looks like this has been fixed
