### ISSUE TITLE
where can i download jar?

### ISSUE THREAD

**Issue by martijintro** [hamcrest/JavaHamcrest#302]
where can i download jar?

**Comment by nhojpatrick** [comment]
available via most dependency management tools using the GAV (GroupdId
ArtifactId Version);
G: org.hamcrest
A: hamcrest
V: 2.2

or download manually the maven repository;
https://search.maven.org/artifact/org.hamcrest/hamcrest/2.2/jar

95% of all projects use a build tool and don't manually download jars, i
think 60% use maven, 30% use gradle, 5% use other tools and 5% do it
manually. stats from the last snyk jvm ecosystem survey.

John

**Comment by martijintro** [comment]
thx!! :-)

**Comment by martijintro** [comment]
closed
