### ISSUE TITLE
"http://hamcrest.org/" says "Bad Gateway"

### ISSUE THREAD

**Issue by 62mkv** [hamcrest/JavaHamcrest#324]
as of 2021-01-05: site responds with

DNS error

DNS error (the host name of the page you are looking for does not exist)

Please check that the host name has been spelled correctly.

**Comment by nhojpatrick** [comment]
@62mkv domain name record was updated on 2020-12-23, and is valid until 2022-01-18 according to whois record. But not sure the real life person is that owns the domain.

Similar to https://github.com/hamcrest/JavaHamcrest/issues/168

Not sure if @sf105 knows who manages the domain.

**Comment by sf105** [comment]
we've just moved to a different registrar. `hamcrest.org` should be up. I'm working on `www` subdomain.

We now have a couple of people who have access. Should there be anyone else?

**Comment by linghengqian** [comment]
> we've just moved to a different registrar. `hamcrest.org` should be up. I'm working on `www` subdomain.
> 
> We now have a couple of people who have access. Should there be anyone else?

- I verified that the site is back and this issue can be closed.

**Comment by tumbarumba** [comment]
Thanks, @linghengqian
