### ISSUE TITLE
Bump source and target compatibility to Java 1.8

### ISSUE THREAD

**Issue by peterdemaeyer** [hamcrest/JavaHamcrest#331]
Hamcrest still supports Java 1.7 source and target compatibility.
Java 1.7 is out of support for years already, I suggest to bump to Java 1.8.
Once that is done, we can finally leverage some useful Java 1.8 features such as lambda expressions in the Hamcrest sources.
Due to quirks and differences with generic type arguments, the change is not as straightforward as it looks, but I'll take a stab at it nonetheless.
I'll prep a PR, but I'll need someone to remove the Java 1.7 compilation from the matrix job in the Travis build.

**Comment by edysli** [comment]
duplicates #207
see also #206
