### ISSUE TITLE
No matcher for empty Map

### ISSUE THREAD

**Issue by Derbeth** [hamcrest/JavaHamcrest#34]
Correct me if I'm wrong, but there is no easy way to assert that an object is an empty map.

I think we need a matcher similar to IsArrayWithSize from org.hamcrest.collection, offering methods like mapWithSize() and emptyMap().

If you confirm there is no such matcher available, I could implement it and offer a pull request.

**Comment by adjohnson916** [comment]
+1 for this feature and for a new release.

**Comment by jadekler** [comment]
+1

**Comment by brandonheck** [comment]
+1

**Comment by mintrupt** [comment]
+1
