### ISSUE TITLE
Hamcrest 3.0?

### ISSUE THREAD

**Issue by dmfs** [hamcrest/JavaHamcrest#353]
I've been using Hamcrest for many years and like it a lot. During the last couple of years, however, I've come across several issues with its design that convinced me to give it a try and create a new assertion framework based on the same idea.

The (early) result can be seen at https://github.com/dmfs/senoritas

Compared to Hamcrest it has a couple of changes in its design. One of the most important improvements over Hamcrest is, that, in case of a mismatch, retrieving the mismatch description doesn't require a second call to the Matcher.

If there is interest, I'd be happy to "donate" it as the basis for Hamcrest 3.0. Otherwise I'd just maintain it as an alternative project to Hamcrest.

**Comment by graemeg** [comment]
Is Hamcrest still being developed? The last release [2.2] is all the way back in 2019. I know Hamcrest has been around for many years, so code base is most likely very stable, thus less commits. But in the same light, I see there are a LOT of pull requests for improvements that have not been actioned.
![image](https://user-images.githubusercontent.com/72053/150676620-fea51c2e-02db-4b10-9ae0-ffa0a2889c0d.png)

**Comment by dmfs** [comment]
Just a quick update: in the meantime, I've published the lib as a new project under https://github.com/saynotobugsorg/confidence The senoritas repo is no longer maintained.

**Comment by tumbarumba** [comment]
New release is imminent
