### ISSUE TITLE
Conflicting license declarations

### ISSUE THREAD

**Issue by thisisatestuseraccount** [hamcrest/JavaHamcrest#355]
Hi there,

While checking open source licenses used by my application's dependencies, I noticed Hamcrest 1.3 was published with an odd license declaration, "[New BSD License](http://www.opensource.org/licenses/bsd-license.php)". This should have been "2-Clause BSD License", but it is published now.

It looks like build.gradle has been updated to "[BSD License 3](http://opensource.org/licenses/BSD-3-Clause)" but the LICENSES.txt in the repository is still the "2-Clause BSD License".

LICENSES.txt should contain the 3-Clause BSD License and build.gradle should reference "3-Clause BSD License" as the license name. Our Java plugin for open source license reporting now works around these issues, but it might be convenient for other people inspecting their licenses.

**Comment by vlsi** [comment]
Relevant issue: https://github.com/hamcrest/JavaHamcrest/issues/264
