### ISSUE TITLE
Matcher checking a string matches a regular expression

### ISSUE THREAD

**Issue by Derbeth** [hamcrest/JavaHamcrest#36]
I cannot find any class allowing me to write my tests like:

```
String actual = tested.buildUrlWithRandomPort("foo", "bar");
assertThat(actual, matchesRegex("^foo://bar:\\d+/$");
// fails with a message like:
// expected <foo://bar:/> to match a regular expression <^foo://bar:\d+/$>
```

I think that Hamcrest Library should offer matchesReges() together with containsString(), endsWith() and startsWith().

Is there a matcher like this available in the master branch? If not, I could write one (something similar to [Hamcrest Regex Matcher](http://piotrga.wordpress.com/2009/03/27/hamcrest-regex-matcher/)) and create a pull request.

**Comment by jm2dev** [comment]
Assuming there is no matcher for regular expressions, you may consider to rewrite your assertion to something like this:
```java
assertThat("Expected result matches regular expression", 
  expected.matches(regularExpression),
  is(true));
```

**Comment by alexec** [comment]
This would be awesome, one of the great thing about Hamcrest is the clear diagnostics.

**Comment by sf105** [comment]
@jm2dev I don't understand your point. Where does the actual value go? Also, if it fails, you just get an expected: true, was: false.

**Comment by adjohnson916** [comment]
+1

**Comment by edbrannin** [comment]
It turns out this was released as part of `java-hamcrest` 2.0.0.0 -- you'll also want to add `hamcrest-junit` to your project if you upgrade from 1.3, and use its `assertThat()` instead of the one in jUnit 4.

**Comment by tomwhoiscontrary** [comment]
Is Hamcrest 2 actually a thing? I thought it was an abortive sally.

**Comment by edbrannin** [comment]
There doesn't seem to be, but it's published to Maven Central.  I was able to put it & the new JUnit integration in `pom.xml` and get my project building.

The main issue was I couldn't `import static org.junit.Assert.*;` anymore (for older test cases that still use `assertEquals`, etc.)  because the two different `assertThat()` implementations got ambiguous.

**Comment by rdp** [comment]
For followers, confirm there is a `MatchesPattern.matchesPattern` in 2.1, thank you!

**Comment by parameshjava** [comment]
> matchesRegex

There is no such method, can you please let me know which version hamcrest you are refering?
