### ISSUE TITLE
Compatibility in java versions

### ISSUE THREAD

**Issue by yuuresuzuki** [hamcrest/JavaHamcrest#409]
Hi

I migrate our project from java 8 to java 11.

We use javahamcrest in our project.

So, I would like to know which version of javahamcrest corresponds to which version of java

Thank you.

**Comment by tumbarumba** [comment]
The latest version of Hamcrest is 2.2. It was compiled to be compatible with the 1.7 Java bytecode. As Java is fully backwards compatible, Hamcrest 2.2 can be used with all currently supported versions of Java.

We are looking to create a new version of Hamcrest, probably targeting Java 1.8 bytecode. When we do that, it will likely be called Hamcrest 3.0

**Comment by yuuresuzuki** [comment]
Thank you for your response. It was very helpful for me.
