### ISSUE TITLE
CoreMatchers constructor is now private

### ISSUE THREAD

**Issue by cushon** [hamcrest/JavaHamcrest#427]
The javadoc cleanup change in 21a05292a873c87424d7a3aca94a40babc899bc7 also added a few private constructors, including to `CoreMatchers`:

https://github.com/hamcrest/JavaHamcrest/blob/21a05292a873c87424d7a3aca94a40babc899bc7/hamcrest/src/main/java/org/hamcrest/CoreMatchers.java#L14-L17

This is a breaking change, I found at least one case of a classes extending `CoreMatchers`:

https://github.com/chromium/chromium/blob/52e4ac4401a6477a9737681e27c6d01ff3ca789f/base/test/android/javatests/src/org/chromium/base/test/util/Matchers.java#L17

Was this deliberate? It isn't obviously related to the other javadoc changes in that commit. If it is deliberate, it could be worth mentioning separately in the release note for the next release.

**Comment by tumbarumba** [comment]
Thanks for pointing that out, @cushon. I was cleaning up all warnings from the javadoc compiler. The warning was something like "default constructor with no javadoc". I can't quite remember exactly. It's probably worth reverting that particular change. I don't want to cause unnecessary breakage.
