### ISSUE TITLE
anyOf does not work in Java 8

### ISSUE THREAD

**Issue by dhumeniuk** [hamcrest/JavaHamcrest#80]
I'm trying to upgrade to Java 8 and now any assertions using anyOf do not work.

```
assertThat("hello", anyOf(is("hello"), is("bye")));
```

I get the message:

> The method anyOf(Matcher<capture#1-of ? super String>, Matcher<capture#2-of ? super String>) is undefined for the type TestPushEventMessage

I also tried:

```
assertThat("hello", anyOf("hello", "bye"));
```

And get the message:

> The method anyOf(Matcher<T>, Matcher<? super T>) in the type Matchers is not applicable for the arguments (String, String)

**Comment by wlund-pivotal** [comment]
Could someone explain how they fixed the problem?  I am having the same error when I import the project and the project pulled in:
* hamcrest-junit-2.0.0.jar
* java-hamcrest-2.0.0.jar
* hamcrest-library-1.3.jar
* hamcrest-core-1.3.jar
What needs to change to fix the TopologyTest.java?
