### ISSUE TITLE
Add matchers for JDK 8 Optionals

### ISSUE THREAD

**Issue by odrotbohm** [hamcrest/JavaHamcrest#82]
There's a Hamcrest-Extras library that has [matchers](https://github.com/gkonst/hamcrest-extras#contents) for Guava's `Optional`. It would be cool to have the standard Hamcrest library provide these kinds of matchers for the pure JDK 8 `Optionals` as well.

**Comment by michaelom** [comment]
+1

**Comment by HolyHaddock** [comment]
:+1:

**Comment by npryce** [comment]
Yes, but not in core, because we support old versions of the Java language that is still used in embedded systems.  Matchers for Java 8 classes will have to go in their own add-on library for now.

**Comment by olivergierke** [comment]
You can have support for Java 8 types but keep compatibility with former version if you just use a JDK 8 to compile the code with e.g. 1.6 target. If the code using the newly introduced types is in dedicated classes, this doesn't cause any issues. Spring Framework makes heavy use of this technique.

**Comment by reardonm** [comment]
:+1:

**Comment by NarendraPathai** [comment]
I have some String related utilities that I have created for my personal use. I would love to contribute those. Have we decided the way we have to package those classes? Will it be an extra library for 1.8 as well?

**Comment by npryce** [comment]
I suggest publishing them as an extension library to start with.

**Comment by npathai** [comment]
I have an initial implementation in https://github.com/npathai/hamcrest-jdk8-extras
Please go through it and provide some inputs.

**Comment by scheffield** [comment]
@npryce @npathai 
https://github.com/npathai/hamcrest-jdk8-extras looks good, despite the double execution of the matcher in `isPresentAnd(Matcher)`. Is there a chance to get it into hamcrest soon?

**Comment by npathai** [comment]
@scheffield Great. I will get to it soon n remove double execution. I have been busy lately. I will change it this weekend.

**Comment by npathai** [comment]
@scheffield I have resolved the issue. I will further refine the implementation if I get some reviews.

**Comment by npathai** [comment]
Does anyone feel we need matchers for new DateTime API of Java8?

**Comment by matteprl** [comment]
@npathai I would rather see your extras merged into core project, but I think you should cover it, since you called your project "jdk8" :)

**Comment by npathai** [comment]
@matteprl Yes I would like that too. But I didn't get your point.

**Comment by stefanbirkner** [comment]
@npathai's hamcrest-jdk8-extras has been renamed to https://github.com/npathai/hamcrest-optional.

**Comment by matteprl** [comment]
@npathai 
@stefanbirkner Thank you for information. I know that library is single file project. But have you considered putting it into maven? I like to keep my dependencies managed, and some people - just like me sometimes use search tool on sites like mvnrepository.com and just type hamcrest jdk8. I think it would also make more people use your library. :)

**Comment by npathai** [comment]
@matteprl Yes we are already considering that. It will be available very soon. Thanks for your inputs.

**Comment by cod3hulk** [comment]
Any update about when this will make it into hamcrest library? I have seen that hamcrest-optional from @npathai  was forked for maven release integration (https://github.com/baev/hamcrest-optional). But I would like to see an "official" hamcrest integration. From my point of view it makes totally sense to integrate the hamcrest-optional lib into hamcrest project.

**Comment by npathai** [comment]
@cod3hulk @matteprl @scheffield 
I have released hamcrest-optional to maven central

```
<dependency>
  <groupId>com.github.npathai</groupId>
  <artifactId>hamcrest-optional</artifactId>
  <version>1.0</version>
</dependency>
```

**Comment by davidxia** [comment]
Hi all. We at Spotify have open-sourced some matchers for Optionals here https://github.com/spotify/java-hamcrest. Hopefully you find these useful and maybe we can even get some of these into upstream.

Let us know if you have questions or ideas.

**Comment by CC007** [comment]
We are now at java 15 going on 16 and Java 7 is now very much end-of-life. Isn't it time to include optionals into the standard java hamcrest library?

**Comment by tumbarumba** [comment]
Closing this issue, discussion can continue on #206
