### ISSUE TITLE
Use @SafeVarargs annotation instad of multiple fixed-arity factory methods that overload varargs method

### ISSUE THREAD

**Issue by npryce** [hamcrest/JavaHamcrest#83]
The overloaded methods were written to reduce compile warnings in client code.  The @SafeVarargs annotation that was introduced in Java 7 suppresses them altogether.

This will change the ABI, but code will still be source compatible.

**Comment by lukeu** [comment]
I'm currently hitting warnings with `IsIterableContainingInOrder.contains`

Should `@SafeVarArgs` be added to this and other methods also? I.e. should this fix be extended to annotate methods which might not have had overloads to begin with?

_(Or might it be that these methods are not actually safe to annotate this way...?)_

**Comment by kwin** [comment]
Even with 2.0.0.0 I still do not see the annotation on `org.hamcrest.Matchers.contains(...)` therefore I still get the following warning
`Type safety: A generic array of Matcher<? super something> is created for a varargs parameter`

**Comment by ePaul** [comment]
I think this was closed preliminarily.
I think all of the varargs methods in Matchers could get this annotation, as well as the static methods they are delegating to.
(I don't understand how this changes the ABI ... the method still accepts an array of the upper bound type, right?)

**Comment by kwin** [comment]
@sf105 Would you consider reopening this?

**Comment by sf105** [comment]
Agreed. This have got too confused.

**Comment by arifogel** [comment]
What exactly will be done with this issue? It looks like the current source has the `@SafeVarargs` annotation:
https://github.com/hamcrest/JavaHamcrest/blob/master/hamcrest/src/main/java/org/hamcrest/Matchers.java#L886
Will there ever be another release with this change?
Isn't this issue technically resolved (but not by the original milestone)?

**Comment by tumbarumba** [comment]
Agree, closing this.
