### ISSUE TITLE
Publish as a single JAR

### ISSUE THREAD

**Issue by npryce** [hamcrest/JavaHamcrest#86]
Publish to Maven Central as a single JAR file.  Do not publish separate hamcrest-api and hamcrest-library JARs.

This will make things easier for client projects and simplify the build.

**Comment by josephw** [comment]
> since JUnit was written and compiled against an old version that is not compatible with Hamcrest 2.x

Ah; I was assuming that you wouldn't be breaking compatibility with JUnit. Hamcrest/JUnit is a fairly popular combination (it's the only way I've seen Hamcrest used) so that may slow uptake of any future Hamcrest releases; I'll keep an eye on #92.

**Comment by npryce** [comment]
You will be able to use future releases of Hamcrest with JUnit, as long as you use a compatible version of hamcrest-junit and don't use JUnit methods that rely on Hamcrest's types.  Since hamcrest-junit will duplicate all functionality in JUnit that relies on Hamcrest, nobody will lose any functionality, but there will be a bit of work to change a project's import statements to bind to hamcrest-junit instead of JUnit.
