### ISSUE TITLE
Add String length matcher

### ISSUE THREAD

**Issue by helsing** [hamcrest/JavaHamcrest#90]
Are there other than me that would like to see a simple String length matcher in the core library for the upcoming release?

It was requested already more than a year ago, here https://code.google.com/p/hamcrest/issues/detail?id=191

(Please, let me know if I can help out in any way?)

**Comment by mle-enso** [comment]
Let me know, if you agree with this PR or if something is missing.

**Comment by agebhar1** [comment]
would be awesome if this PR could be merged :smile:

**Comment by derTobsch** [comment]
Just googled it :) because I missed this matcher.

**Comment by sf105** [comment]
It's in.
