### ISSUE TITLE
Decouple the evolution of Hamcrest and JUnit

### ISSUE THREAD

**Issue by npryce** [hamcrest/JavaHamcrest#92]
Evolution of Hamcrest and JUnit has been held back by the dependencies between the two projects. If they can be decoupled, both projects can move forward with less coordination required.

Plan:

 * create a new project (hamcrest-junit, say) that contains a copy of the JUnit code that uses Hamcrest, repackaged somewhere under org.hamcrest (org.hamcrest.junit, say) so that they can live side-by-side with existing JUnit and Hamcrest code.  
 * Deprecate existing code in JUnit that depends on Hamcrest
 * Perhaps deprecate Hamcrest's MatcherAssert class, now that it is duplicated in the hamcrest-junit module.
 * Eventually delete the deprecated code.
 * Run a CI "matrix" that reports the compatibility of Hamcrest and JUnit versions.

The uses of Hamcrest in JUnit are:

 - Assert and Assume in org.junit, for which we'd have to duplicate the methods using matchers as (for instance) MatcherAssert and MatcherAssume
 - ErrorCollector and ExpectedException (and a package-protected supporting class) in org.junit.rules, which we'd have to duplicate.
 - several classes in the org.junit.internal packages, which client code should not be using

**Comment by npryce** [comment]
@SamirTalwar - Code in org.junit.internal will have to be rewritten to remove references to Hamcrest.  We're not doing anything about internal JUnit implementation details.

**Comment by npryce** [comment]
hamcrest-junit 1.0.0.0-RC1 should appear in maven central soon.

**Comment by marcphilipp** [comment]
@npryce Thanks for taking a first step into this direction. I'm one of the maintainers of JUnit. We have had some thoughts about modularizing JUnit. junit-hamcrest would have been a potential outcome of this.

@stefanbirkner posted a link to your blog post on the JUnit mailing list. One users replied with a number of concerns: https://groups.yahoo.com/neo/groups/junit/conversations/messages/24626. I share some of those concerns.

@npryce Do you have time to take a look?

**Comment by npryce** [comment]
I'll join the JUnit group and give my thoughts

**Comment by npryce** [comment]
@marcphilipp - I posted to the JUnit list but got no response. Did you see the message?

**Comment by marcphilipp** [comment]
@npryce Yes, I did see it. I haven't had time to respond yet, but will do so. I think you have silenced the most

**Comment by npryce** [comment]
Great.  And (of course) I'd be happy for JUnit maintainers to collaborate on hamcrest-junit.

**Comment by marcphilipp** [comment]
We're in the midst of a discussion regarding our plans for JUnit 5. We will definitely get back to you. It might take some time, though. 

If you need feedback from us, please don't hesitate to ping us over at junit-team/junit or through the mailing list.

**Comment by kcooney** [comment]
Hi. I am another of the maintainers of JUnit.

Any chance that java-hamcrest can depend on JDK 6, not JDK 7? JUnit us used in a number of environments (GWT, Android, possibly Java ME). Some of our users have large systems, and cannot quickly update their JDK.

The JUnit teams' current plan was to have JUnit 5 require JDK 6. (JUnit 4.x only requires JDK 5). If we are to start to remove the dependency from Hamcrest, we might end up migrating the tests of JUnit itself use hamcrest-junit. It would be great to start that process soon, but we rather not have JUnit 5 require JDK 7.

**Comment by marcphilipp** [comment]
I've opened #105 regarding the JDK 7 requirement.

**Comment by marcphilipp** [comment]
**Proposal:** In addition to what has been released so far, we/you release hamcrest-junit 1.3 which depends on hamcrest-core 1.3. Both artifacts are compiled with target JDK 1.6.

That would not only allow JUnit to keep it's test dependency on hamcrest but in addition would make it possible to use JUnit 5 (which will not depend on Hamcrest anymore) along with hamcrest-junit 1.3 on JDK 6.

Does that make sense?

**Comment by npryce** [comment]
There is already a hamcrest-junit 1.0.0.0 release that depends on hamcrest 1.3.  If that is not compatible with JDK 1.6, I can publish a new release (1.0.0.1) that is.

**Comment by npryce** [comment]
I've created a 1.x.x.x branch of hamcrest-junit and Travis is building that with Java 1.6. https://travis-ci.org/hamcrest/hamcrest-junit/builds/64050527

I'll publish a 1.0.0.1 release from that branch built with 1.6

**Comment by marcphilipp** [comment]
Before you release it we should fix hamcrest/hamcrest-junit#5 first, right?

**Comment by npryce** [comment]
I've released Hamcrest-JUnit 1.0.0.1, which is compiled with JDK 1.6.

I didn't notice your comment. We can publish other releases (1.0.1.0, 2.0.1.0) with the generic error collector.
